name: Build and Release

on:
  push:
    branches:
      - main  
    tags:
      - 'v1.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl https://bun.sh/install | bash
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies with Bun
        run: bun install

      - name: Compile the project
        run: bun run compile

      - name: Install vsce (Visual Studio Code Extension CLI)
        run: bun add -g vsce

      - name: Package VSIX
        run: vsce package

      - name: Create ZIP package
        run: |
          if [ -d "out" ]; then
            zip -r rusty-extension.zip out/ src/ package.json README.md LICENSE
          else
            echo "The 'out' directory does not exist."
            exit 1
          fi

      - name: Create Git Tag
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          TAG="v$(date +'%Y.%m.%d').$(git rev-parse --short HEAD)"
          git tag $TAG
          git push origin $TAG

      - name: Upload release files to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rusty-extension.zip
            *.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}