name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bun
        run: |
          curl https://bun.sh/install | bash
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Compile the project
        run: bun run compile

      - name: Install vsce
        run: bun add -g vsce

      - name: Package VSIX
        run: vsce package

      - name: Create zip package
        run: zip -r rusty-extension.zip out/ extension.js package.json README.md LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
            rusty-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}